services:
  low-bar-brawlers:
    image: oven/bun:slim
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - .:/app
      - drawing_data:/app/server/drawing.json
    working_dir: /app
    command: ["sh", "-c", "bun install && bun run build && bun run start:server"]
    networks:
      - npm

volumes:
  drawing_data:

networks:
  npm:
    external: true
    name: npm_network